#SPDX-License-Identifier: MIT-0
---
# tasks file for base
- name: Update the APT package index
  ansible.builtin.apt:
    update_cache: yes
  register: update_result
  notify: Upgrade all installed packages