#SPDX-License-Identifier: MIT-0
---
# tasks file for base
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
  register: update_result
  notify: Upgrade all installed packages

- name: Ensure base set of packages are installed
  ansible.builtin.apt:
    name:
      - curl
      - net-tools
      - git
      - jq
    state: latest

# - name: enable ssh service on boot
#   service:
#     name: ssh
#     enabled: true
#     state: started

- name: Check if a reboot is needed for Debian-based systems
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Report if reboot is needed.
  ansible.builtin.debug:
    msg: Rebooting the server, please wait.
  when: reboot_required.stat.exists

- name: Reboot the server if needed
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible because of reboot required file."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists